<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

    public function findMy($id)
    {
        $db=$this
            ->createQueryBuilder('a')
            ->where('a.id < :id ')
            ->orderBy('a.title', 'ASC')
            ->setParameter('id', $id)
            ->getQuery()
        ;
        return $db->getResult();
    }
}
