<?php

namespace AppBundle\Repository;

/**
 * FullOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FullOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
