<?php

namespace AppBundle\Repository;

/**
 * OrderUserGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderUserGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
